### ISSUE TITLE
v1.11.1 SalesforceLogin() got an unexpected keyword argument 'privatekey'

### ISSUE THREAD

**Issue by PracticalGeek1** [simple-salesforce/simple-salesforce#467]
I've been using v1.10.1, but after upgrade to v1.11.1, this no longer works:
```
sf = Salesforce(username=username,
                    consumer_key=consumer_key,
                    privatekey_file='svrkey.pem')
```
error says SalesforceLogin() got an unexpected keyword argument 'privatekey', but isn't it supposed to be optional?
P.s. I'm running python 3.8

**Comment by jon-wobken** [comment]
@PracticalGeek1  - I can't replicate this on my side. It is optional, I would recommend a fresh install and see if the issue persists.
